# Site settings
title: Firefly III
email: thegrumpydictator@gmail.com
description: > 
  Firefly III is a personal finances manager.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "https://firefly-iii.github.io" # the base hostname & protocol for your site
twitter_username: 
github_username:  JC5

# Gems
gems:
  - jekyll-paginate

#Others
markdown: kramdown
